### ISSUE TITLE
The bot is "reply deboosted" and the profile is marked sensitive

### ISSUE THREAD

**Issue by ghost** [noahkrever/DefineEveryWord#1]
The bot's replies now show as "Offensive Content". A possible workaround is to disable sensitive media in the settings.
![image](https://user-images.githubusercontent.com/83127604/115962368-0a2d2c80-a4e9-11eb-9e69-c8fe67dcea56.png)

**Comment by ghost** [comment]
This is what I'm talking about

![Screenshot_20210427-110609_Twitter](https://user-images.githubusercontent.com/83127604/116264839-9c7f3b80-a748-11eb-893a-93a313ccb50b.jpg)
![Screenshot_20210427-110613_Twitter](https://user-images.githubusercontent.com/83127604/116264848-9e48ff00-a748-11eb-92b9-89b780d8e70b.jpg)

**Comment by liamengland1** [comment]
Nothing can be done. Twitter shadowban.

**Comment by ghost** [comment]
> Nothing can be done. Twitter shadowban.

Is this on or off? Because it happens when people have their tweets as sensitive. Whenever a photo isn't sent, the bot isn't flagged.
![20210427_192422](https://user-images.githubusercontent.com/83127604/116324495-40d7a100-a78e-11eb-86e2-d280199125aa.jpg)
